apiVersion: batch/v1
kind: Job
metadata:
  name: foodapp-seed
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: sam840/foodapp-backend:latest
          command: ["node", "seed.js"]
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/foodapp"
